version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepfake-app-dev
    volumes:
      - .:/app  # Mount current dir (hot-reload)
    ports:
      - "8081:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
