version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepfake-app
    ports:
      - "8000:8000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
